# Values file for todo-api chart
app-deployment:
  image:
    registry: quay.io/pnminh232
    path: todo-api
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "main-2cd97a3"
  imagePullSecrets: 
    - name: quay
  command:
    - /bin/bash
    - -c
    - |-
      source /secrets/ocp-secrets && \
      QUARKUS_DATASOURCE_USERNAME=$DATABASE_USERNAME \
      QUARKUS_DATASOURCE_PASSWORD=$DATABASE_PASSWORD \
      QUARKUS_DATASOURCE_JDBC_URL="jdbc:postgresql://todo-db:5432/$DATABASE_NAME" \
      exec /usr/local/s2i/run
  livenessProbe:
    httpGet:
      path: /q/health/live
      port: http
    initialDelaySeconds: 30
  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: http
    initialDelaySeconds: 30
  azKeyVault:
    enabled: true
    secretFileDir: /secrets