# Values file for todo-db chart
app-deployment:
  image:
    registry: quay.io/pnminh232
    path: postgres-nonroot
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.0"
  imagePullSecrets: 
    - name: quay
    - name: wwt-docker
  env:
    - name: PGDATA
      value: /temp/data
  command:
    - /bin/bash
    - -c
    - |-
      source /secrets/ocp-secrets && \
      POSTGRES_DB=$DATABASE_NAME \
      POSTGRES_USER=$DATABASE_USERNAME \
      POSTGRES_PASSWORD=$DATABASE_PASSWORD \
      exec docker-entrypoint.sh postgres
  livenessProbe:
    tcpSocket:
      port: 5432
    initialDelaySeconds: 30
  readinessProbe:
    tcpSocket:
      port: 5432
    initialDelaySeconds: 30
  ports:
    - name: db
      containerPort: 5432
      protocol: TCP
  service:
    type: ClusterIP
    ports: 
      - name: db
        protocol: TCP
        port: 5432
        targetPort: db
  route:
    enabled: false
  azKeyVault:
    enabled: true
    loginSecretName: azure-creds
    vaultKeys:
      - ocp-secrets
      - ocp-github-secrets
    image:
      path: docker.wwt.com/az-keyvault
      tag: main-ae7190d